### PR TITLE
[Modal] remove option that seems outdated

### PR DESCRIPTION
**Pull request by hamirmahal**

### CODE REVIEW

**Comment by hamirmahal** [comment]
# Problem

[Screencast from 02-19-2024 02:12:15 PM.webm](https://github.com/skiff-org/skiff-apps/assets/43425812/e3f27b23-a042-4a2b-9ba7-2229f3d619a1)

**Comment by profilelag** [comment]
I have a feeling that this is linking to a blank link because they are not planning on developing the project any further due to the deal with notion. It did go to something, but they have removed it sometime since February 7th

**Comment by hamirmahal** [comment]
Right, I was just reading about the deal with Notion.

**Comment by wakaztahir** [comment]
Hi, everybody, I've been tickering with this project, BUT the build errors are so many.

What do I need to do to just start the project, There's no build guide, There are missing graphql types.

**Comment by profilelag** [comment]
I've actually been getting prosemirror errors

**Comment by wakaztahir** [comment]
The project is unbuildable, The project contains yarn cache folder which has native dependencies that have been built for a specific Os and don't work on mine.

The build command fails on multiple levels for multiple packages.

The project also has missing graphql types.

This makes the project useless, Please fix this.

**Comment by profilelag** [comment]
I'm working on fixing skiff-apps, but on my fork, I'll send it to you when I finish it

**Comment by profilelag** [comment]
Working on it for my OpenSkiff project to replace skiff, lol

**Comment by profilelag** [comment]
@wakaztahir I recommend you join this: https://discord.gg/yd4MkF2R5d

**Comment by hamirmahal** [comment]
@amilich I'm going through my unresolved pull requests. Are you open to this change?

**Review by amilich — APPROVED** [review]

**Pull request merged**
